import os
from dotenv import load_dotenv

load_dotenv()

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
COSMOS_DB_ENDPOINT = os.getenv('COSMOS_DB_ENDPOINT')
COSMOS_DB_KEY = os.getenv('COSMOS_DB_KEY')
COSMOS_DB_DATABASE = os.getenv('COSMOS_DB_DATABASE')
COSMOS_DB_EXPENSES_CONTAINER = os.getenv('COSMOS_DB_EXPENSES_CONTAINER')
COSMOS_DB_BUDGET_CONTAINER = os.getenv('COSMOS_DB_BUDGET_CONTAINER')
